const mock = [{
  "kind":"books#volume",
  "id":"O5o7cSsC5W0C",
  "etag":"GPHvaSzWV58",
  "selfLink":"https://www.googleapis.com/books/v1/volumes/O5o7cSsC5W0C",
  "volumeInfo":{
    "title":"Data Uses in Health Planning",
    "authors":[
      "Edward F. R. Hearle"
    ],
    "publishedDate":"1970",
    "industryIdentifiers":[
      {
        "type":"OTHER",
        "identifier":"PURD:32754063270494"
      }
    ],
    "readingModes":{
      "text":false,
      "image":true
    },
    "pageCount":48,
    "printType":"BOOK",
    "categories":[
      "Health surveys"
    ],
    "maturityRating":"NOT_MATURE",
    "allowAnonLogging":false,
    "contentVersion":"1.1.0.0.full.1",
    "imageLinks":{
      "smallThumbnail":"http://books.google.com/books/content?id=O5o7cSsC5W0C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
      "thumbnail":"http://books.google.com/books/content?id=O5o7cSsC5W0C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    },
    "language":"en",
    "previewLink":"http://books.google.ro/books?id=O5o7cSsC5W0C&pg=PA33&dq=Head+Fi&hl=&cd=8&source=gbs_api",
    "infoLink":"https://play.google.com/store/books/details?id=O5o7cSsC5W0C&source=gbs_api",
    "canonicalVolumeLink":"https://market.android.com/details?id=book-O5o7cSsC5W0C"
  },
  "saleInfo":{
    "country":"RO",
    "saleability":"FREE",
    "isEbook":true,
    "buyLink":"https://play.google.com/store/books/details?id=O5o7cSsC5W0C&rdid=book-O5o7cSsC5W0C&rdot=1&source=gbs_api"
  },
  "accessInfo":{
    "country":"RO",
    "viewability":"ALL_PAGES",
    "embeddable":true,
    "publicDomain":true,
    "textToSpeechPermission":"ALLOWED",
    "epub":{
      "isAvailable":false
    },
    "pdf":{
      "isAvailable":true,
      "downloadLink":"http://books.google.ro/books/download/Data_Uses_in_Health_Planning.pdf?id=O…C5W0C&hl=&output=pdf&sig=ACfU3U1aqLx93yuuPe1q9MQhfM3keMU9SQ&source=gbs_api"
    },
    "webReaderLink":"http://books.google.ro/books/reader?id=O5o7cSsC5W0C&hl=&printsec=frontcover&output=reader&source=gbs_api",
    "accessViewStatus":"FULL_PUBLIC_DOMAIN",
    "quoteSharingAllowed":false
  },
  "searchInfo":{
    "textSnippet":"Check &quot;Yes&quot; or &#39;&#39;No&#39;&#39; for each person listed it] <b>Head</b> of household 1 D Now <br>\nmarried 2 E Wife of <b>head</b> of household 1l:l Male 2 [I] Widowed 1 :] Yes 3 [1 Son or <br>\ndaughter of <b>head</b> 2 <b>F I</b> mnth 3 Cl Divorced 4 C] Other relative of <b>head</b> &#39;3 ema e 4 <br>\nU&nbsp;..."
  }
},{
  "kind":"books#volume",
  "id":"ddsRAAAAIAAJ",
  "etag":"poRv/TbIpNg",
  "selfLink":"https://www.googleapis.com/books/v1/volumes/ddsRAAAAIAAJ",
  "volumeInfo":{
    "title":"Nathan Bailey's Dictionary, English-German and German-English: Th. Deutsch-englisch",
    "authors":[
      "Nathan Bailey",
      "Johann Anton Fahrenkrueger"
    ],
    "publishedDate":"1801",
    "industryIdentifiers":[
      {
        "type":"OTHER",
        "identifier":"NYPL:33433069238818"
      }
    ],
    "readingModes":{
      "text":false,
      "image":true
    },
    "printType":"BOOK",
    "categories":[
      "German language"
    ],
    "maturityRating":"NOT_MATURE",
    "allowAnonLogging":false,
    "contentVersion":"full-1.0.0",
    "imageLinks":{
      "smallThumbnail":"http://books.google.com/books/content?id=ddsRAAAAIAAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
      "thumbnail":"http://books.google.com/books/content?id=ddsRAAAAIAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api"
    },
    "language":"en",
    "previewLink":"http://books.google.ro/books?id=ddsRAAAAIAAJ&pg=PA393&dq=Head+Fi&hl=&cd=9&source=gbs_api",
    "infoLink":"https://play.google.com/store/books/details?id=ddsRAAAAIAAJ&source=gbs_api",
    "canonicalVolumeLink":"https://market.android.com/details?id=book-ddsRAAAAIAAJ"
  },
  "saleInfo":{
    "country":"RO",
    "saleability":"FREE",
    "isEbook":true,
    "buyLink":"https://play.google.com/store/books/details?id=ddsRAAAAIAAJ&rdid=book-ddsRAAAAIAAJ&rdot=1&source=gbs_api"
  },
  "accessInfo":{
    "country":"RO",
    "viewability":"ALL_PAGES",
    "embeddable":true,
    "publicDomain":true,
    "textToSpeechPermission":"ALLOWED",
    "epub":{
      "isAvailable":false
    },
    "pdf":{
      "isAvailable":true,
      "downloadLink":"http://books.google.ro/books/download/Nathan_Bailey_s_Dictionary_English_Ge…AIAAJ&hl=&output=pdf&sig=ACfU3U0KyC9ORt-EHvxxS1fKfL_fW2uviw&source=gbs_api"
    },
    "webReaderLink":"http://books.google.ro/books/reader?id=ddsRAAAAIAAJ&hl=&printsec=frontcover&output=reader&source=gbs_api",
    "accessViewStatus":"FULL_PUBLIC_DOMAIN",
    "quoteSharingAllowed":false
  },
  "searchInfo":{
    "textSnippet":"<b>fi</b> d)S) m. ox; fid) fen, pi. oxen* ein jnngerfid)« bullock; em bummer fid)8 bufTle-<br>\n<b>head</b>, dunce. fid) fen a uge, n. eye of an ox; ®e/ batfenes buttered egg; eine &lt;J)<br>\nffanje oxeye. fidjfeilbraten, m. roast beef. <b>fi</b> djfenfieber, n. haben to be lazy after&nbsp;..."
  }
}]

export default mock;
